services:
  uki-dev:
    build: .
    ports:
      - "5111:3001"
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./public/img/logos:/app/public/img/logos
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
    restart: unless-stopped
