import { app } from './src/App.js'
import * as scribdFlag from './src/const/ScribdFlag.js'

const flags = [scribdFlag.DEFAULT, scribdFlag.IMAGE]

if (process.argv.length >= 3) {
    let url;
    let flag;
    let outputPath;
    for (let i = 2; i < process.argv.length; i++) {
        if (flags.includes(process.argv[i])) {
            flag = process.argv[i]
        } else if (process.argv[i].startsWith('--output=')) {
            outputPath = process.argv[i].split('=')[1]
        } else {
            url = process.argv[i]
        }
    }
    await app.execute(url, flag, outputPath)
} else {
    console.error(`
Usage: npm start [options] url
Options:
  /i        image-based: generated by image snapshots taken for pages on scribd.com
  --output=path  specify output directory
    `)
}